
name: Download and Release File

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the file to download'
        required: true

jobs:
  download_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download file
        id: download_file
        uses: actions/download-artifact@v3
        with:
          url: ${{ github.event.inputs.file_url }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        with:
          tag_name: 'v1.0.0' # Replace with your desired tag name
          release_name: 'Release v1.0.0' # Replace with your desired release name
          body: 'This is a test release.' # Replace with your desired release notes
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.download_file.outputs.file_path }}
          asset_name: ${{ steps.download_file.outputs.file_name }}
          asset_content_type: application/octet-stream
