name: Download File and Release

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL của file cần tải'
        required: true
      file_name:
        description: 'Tên lưu file đã tải (để trống để sử dụng tên file gốc từ URL)'
        required: false
        default: ''

jobs:
  download_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Identify file name and extension
        id: identify_file
        run: |
          FILE_URL="${{ github.event.inputs.file_url }}"
          FILE_NAME=$(curl -sI "$FILE_URL" | grep -o -E 'filename=.*$' | sed -e 's/filename=//')
          if [ -z "$FILE_NAME" ]; then
            FILE_NAME=$(basename "$FILE_URL")
            if [[ ${#FILE_NAME} -gt 50 || ! "$FILE_NAME" == *.* ]]; then
              FILE_NAME="temp.file"
              echo "Không lấy được tên file từ URL hoặc header." >> $GITHUB_ENV
            fi
          fi
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
          echo "file_name=$FILE_NAME" >> $GITHUB_ENV

          MIME_TYPE=$(curl -sI "$FILE_URL" | grep -oP 'Content-Type: \K.*')
          EXTENSION="${MIME_TYPE##*/}"
          echo "FILE_NAME_WITH_EXT=${FILE_NAME}" >> $GITHUB_ENV
          echo "FILE_EXTENSION=$EXTENSION" >> $GITHUB_ENV

      - name: Download file
        run: wget "${{ github.event.inputs.file_url }}" -O "${{ env.FILE_NAME_WITH_EXT }}"

      - name: Rename file if necessary
        if: ${{ github.event.inputs.file_name != '' }}
        run: |
          FILE_NAME="${{ github.event.inputs.file_name }}"
          FILE_EXTENSION="${{ env.FILE_EXTENSION }}"
          if [[ "$FILE_NAME" == *.* ]]; then
            mv "${{ env.FILE_NAME_WITH_EXT }}" "$FILE_NAME"
            echo "FINAL_FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
          else
            mv "${{ env.FILE_NAME_WITH_EXT }}" "${FILE_NAME}.${FILE_EXTENSION}"
            echo "FINAL_FILE_NAME=${FILE_NAME}.${FILE_EXTENSION}" >> $GITHUB_ENV

      - name: Determine new release version
        run: echo "release_version=v1.0.$(( ${{ github.run_number }} + 1 ))" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        with:
          tag_name: ${{ env.release_version }}
          release_name: Release ${{ env.release_version }}
          body: |
            File URL: ${{ github.event.inputs.file_url }}
            !File Preview
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/${{ env.FINAL_FILE_NAME }}
          asset_name: ${{ env.FINAL_FILE_NAME }}
          asset_content_type: application/octet-stream

      - name: Update release notes with preview
        run: |
          ASSET_URL=$(jq --raw-output '.browser_download_url' <<< "${{ steps.upload_release_asset.outputs }}")
          FILE_EXTENSION="${{ env.FILE_EXTENSION }}"
          if [[ "$FILE_EXTENSION" =~ ^(jpg|png|gif)$ ]]; then
            PREVIEW_TEXT="![Image Preview]($ASSET_URL)"
          elif [[ "$FILE_EXTENSION" =~ ^(mp3|wav)$ ]]; then
            PREVIEW_TEXT="[Listen to Audio]($ASSET_URL)"
          elif [[ "$FILE_EXTENSION" =~ ^(mp4|avi)$ ]]; then
            PREVIEW_TEXT="[Watch Video]($ASSET_URL)"
          else
            PREVIEW_TEXT="File URL: $ASSET_URL"
          fi
          gh release edit "${{ env.release_version }}" --add "$PREVIEW_TEXT"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
