name: Download File and Release

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the file to download'
        required: true
        default: ''
      replace_file_name:
        description: 'Replacement file name (leave blank to use original filename from URL)'
        required: false
        default: ''

jobs:
  download_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true  # Thiết lập để sử dụng Git LFS

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs track "${{ github.event.inputs.file_name }}"
          git add .gitattributes
          git commit -m "Setup Git LFS"
          git push

      - name: Determine file name
        id: determine_file_name
        run: |
          FILE_URL="${{ github.event.inputs.file_url }}"
          FILE_NAME=$(basename "${FILE_URL}" | cut -c 1-50)
          if [ ${#FILE_NAME} -eq 0 ]; then
            echo "Could not determine file name, using temporary name 'temp.file'"
            FILE_NAME="temp.file"
          fi
          echo "::set-output name=file_name::${FILE_NAME}"

      - name: Download file
        run: wget "${{ github.event.inputs.file_url }}" -O "${{ steps.determine_file_name.outputs.file_name }}"

      - name: Determine new file name and extension
        id: determine_new_file_name
        if: ${{ github.event.inputs.replace_file_name != '' }}
        run: |
          NEW_FILE_NAME="${{ github.event.inputs.replace_file_name }}"
          EXTENSION=$(echo "${{ steps.determine_file_name.outputs.file_name }}" | cut -d '.' -f 2-)
          if [ ${{ github.event.inputs.replace_file_name }} != ${{ github.event.inputs.replace_file_name | cut -d '.' -f 1 }} ]; then
            NEW_FILE_NAME="${{ github.event.inputs.replace_file_name }}"
          else
            NEW_FILE_NAME="${{ github.event.inputs.replace_file_name }}.${{ EXTENSION }}"
          fi
          echo "::set-output name=new_file_name::${NEW_FILE_NAME}"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          body: |
            File URL: ${{ github.event.inputs.file_url }}
            New file name: ${{ steps.determine_new_file_name.outputs.new_file_name }}
          draft: false
          prerelease: false
