name: High-Speed Download and Release

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the file to download'
        required: true
      replacement_name:
        description: 'Replacement name for the file (optional)'
        required: false

jobs:
  download-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download File
        id: download
        run: |
          url="${{ github.event.inputs.file_url }}"
          name="${{ github.event.inputs.replacement_name }}"
          if [ -z "$name" ]; then
            name=$(basename "$url")
          elif [[ "$name" != *.* ]]; then
            extension="${url##*.}"
            name="$name.$extension"
          fi
          curl -L -o "$name" "$url" --progress-bar

      - name: Upload to Release
        id: upload-release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.download.outputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release Notes
        run: |
          file_name="${{ steps.download.outputs.name }}"
          extension="${file_name##*.}"
          case "$extension" in
            mov|mp4|mkv|avi|wmv|flv|mpg|mpeg|3gp|m4v|webm|ogv|rm|rmvb|ts|vob|divx|m3u8)
              echo "Preview Video: $file_name" >> release_notes.md
              ;;
            jpg|jpeg|png|gif|bmp|tiff|svg|webp|psd)
              echo "Preview Image: $file_name" >> release_notes.md
              ;;
            mp3|wav|ogg|flac|aac|wma|m4a|aiff|alac|opus)
              echo "Preview Audio: $file_name" >> release_notes.md
              ;;
            zip)
              echo "Contents of the ZIP file:" >> release_notes.md
              unzip -l "$file_name" >> release_notes.md
              ;;
          esac
          cat release_notes.md
          
