name: Download File and Release

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the file to download'
        required: true
        default: ''
      file_name:
        description: 'Name to save the downloaded file as (leave blank to use original filename from URL)'
        required: false
        default: ''

jobs:
  download_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true  # Thiết lập để sử dụng Git LFS

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs track "${{ github.event.inputs.file_name }}"
          git add .gitattributes
          git commit -m "Setup Git LFS"
          git push

      - name: Determine file extension
        id: determine_file_extension
        run: |
          FILE_EXTENSION=$(echo "${{ github.event.inputs.file_url }}" | awk -F . '{print $NF}')
          echo "::set-output name=file_extension::$FILE_EXTENSION"

      - name: Determine file name and extension
        id: determine_file_info
        if: ${{ !github.event.inputs.file_name }}
        run: |
          FILE_URL="${{ github.event.inputs.file_url }}"
          FILE_NAME=$(basename "${FILE_URL}")
          echo "::set-output name=file_name::${FILE_NAME}"

      - name: Download file
        run: wget "${{ github.event.inputs.file_url }}" -O "${{ github.event.inputs.file_name || steps.determine_file_info.outputs.file_name }}.${{ steps.determine_file_extension.outputs.file_extension }}"

      - name: Determine new release version
        id: determine_release_version
        run: echo "::set-output name=release_version::v1.0.$(( ${{ github.run_number }} + 1 ))"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.determine_release_version.outputs.release_version }}
          release_name: Release ${{ steps.determine_release_version.outputs.release_version }}
          body: |
            File URL: ${{ github.event.inputs.file_url }}
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/${{ github.event.inputs.file_name || steps.determine_file_info.outputs.file_name }}.${{ steps.determine_file_extension.outputs.file_extension }}
          asset_name: ${{ github.event.inputs.file_name || steps.determine_file_info.outputs.file_name }}.${{ steps.determine_file_extension.outputs.file_extension }}
          asset_content_type: application/octet-stream

      - name: Cleanup
        run: |
          rm -f .gitattributes
          git rm .gitattributes
          git commit -m "Remove .gitattributes" || echo "No changes to commit"
          git push
