name: High-Speed File Downloader and Releaser with Preview Link

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL của file để tải xuống'
        required: true
      file_name:
        description: 'Tên mới cho file (tùy chọn)'
        required: false

jobs:
  download-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get current date and start time
      run: |
        echo "start_time=$(date +"%T")" >> $GITHUB_ENV
        echo "start_date=$(date +"%Y-%m-%d")" >> $GITHUB_ENV

    - name: Download File
      run: |
        start=$(date +%s)
        curl -L ${{ github.event.inputs.file_url }} -o "${{ github.event.inputs.file_name || 'tempfile' }}"
        end=$(date +%s)
        echo "download_duration=$((end-start)) seconds" >> $GITHUB_ENV
      
    - name: Extract File Extension
      if: ${{ github.event.inputs.file_name == '' }}
      run: |
        filename=$(basename ${{ github.event.inputs.file_url }})
        extension="${filename##*.}"
        echo "File extension is $extension"
        echo "extension=$extension" >> $GITHUB_ENV

    - name: Rename File
      run: |
        if [[ -z "${{ github.event.inputs.file_name }}" ]]; then
          mv tempfile $(basename ${{ github.event.inputs.file_url }})
        elif [[ "${{ github.event.inputs.file_name }}" != *.* ]]; then
          filename=$(basename ${{ github.event.inputs.file_url }})
          extension="${filename##*.}"
          mv tempfile "${{ github.event.inputs.file_name }}.$extension"
        else
          mv tempfile "${{ github.event.inputs.file_name }}"
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        release_name: Release-${{ github.run_id }}
        body: |
          File được tải xuống từ: ${{ github.event.inputs.file_url }}
          Xem trước file tại: Preview
          Ngày tải xuống: ${{ env.start_date }}
          Thời gian bắt đầu: ${{ env.start_time }}
          Thời lượng tải xuống: ${{ env.download_duration }} giây
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/${{ github.event.inputs.file_name || 'tempfile' }}.${{ env.extension }}
        asset_name: ${{ github.event.inputs.file_name || 'tempfile' }}.${{ env.extension }}
        asset_content_type: application/octet-stream
        
