name: Test output

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the file to be downloaded'
        required: true
      file_name:
        description: 'Custom file name (leave empty to use the original file name from the URL)'
        required: false
        default: ''

jobs:
  download_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Identify file name and extension
        id: identify_file
        run: |
          FILE_URL="${{ github.event.inputs.file_url }}"
          # Send a request to the URL and parse the response to get the file name
          response=$(curl -sI "$FILE_URL")
          
          # Extract the file name from the response
          FILE_NAME=$(echo "$response")
          echo $FILE_NAME "${{ github.event.inputs.file_url }}"
    
