
name: Remote Upload Workflow

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Nhập URL cần tải xuống'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Đọc thông tin WebDAV từ tệp
      run: |
        WEBDAV_URL=$(cat webdav_info.txt | grep URL | cut -d '=' -f2)
        WEBDAV_USERNAME=$(cat webdav_info.txt | grep USERNAME | cut -d '=' -f2)
        WEBDAV_PASSWORD=$(cat webdav_info.txt | grep PASSWORD | cut -d '=' -f2)
        echo "WEBDAV_URL=$WEBDAV_URL" >> $GITHUB_ENV
        echo "WEBDAV_USERNAME=$WEBDAV_USERNAME" >> $GITHUB_ENV
        echo "WEBDAV_PASSWORD=$WEBDAV_PASSWORD" >> $GITHUB_ENV

    - name: Xác định loại URL và tải xuống
      run: |
        if [[ ${{ github.event.inputs.url }} == *"youtube.com"* || ${{ github.event.inputs.url }} == *"music.youtube.com"* ]]; then
          yt-dlp --extractor-args "youtube:player_client=android" -o "%(title)s.%(ext)s" ${{ github.event.inputs.url }}
        elif [[ ${{ github.event.inputs.url }} == *"/playlist?"* ]]; then
          PLAYLIST_NAME=$(yt-dlp --get-filename -o "%(playlist)s" ${{ github.event.inputs.url }})
          mkdir $PLAYLIST_NAME
          yt-dlp -o "$PLAYLIST_NAME/%(title)s.%(ext)s" ${{ github.event.inputs.url }}
        else
          curl -o file ${{ github.event.inputs.url }}
        fi

    - name: Upload lên WebDAV
      run: |
        if [ -d "$PLAYLIST_NAME" ]; then
          curl -T $PLAYLIST_NAME -u $WEBDAV_USERNAME:$WEBDAV_PASSWORD $WEBDAV_URL/$PLAYLIST_NAME -o /dev/null
        else
          curl -T * -u $WEBDAV_USERNAME:$WEBDAV_PASSWORD $WEBDAV_URL -o /dev/null
        fi

    - name: Dọn dẹp
      run: rm -rf $PLAYLIST_NAME file
      
